export const CLEAR_DATA = "CLEAR_DATA";
export const FETCH_NEXT_PAGE = "FETCH_NEXT_PAGE";
export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
export const FETCH_DATA_END = "FETCH_DATA_END";
export const UPDATE_SEARCH_STRING = "UPDATE_SEARCH_STRING";
